[build]
  publish = "dist/project02-14"  # Replace with your actual Angular app name
  command = "ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
